version: 2
jobs:
  build:
    docker:
      - image: rikorose/gcc-cmake:latest
    working_directory: ~/yards-test
    steps:
      - checkout
      - run:
          name: Create Build Files
          command: |
              cmake -H. -Bbuild
      - run:
          name: Create Binary Files
          command: |
              cmake --build build
      - run:
          name: Run unit tests
          command: |
              ./build/test_unit
